### ISSUE TITLE
Discussion about DI 

### ISSUE THREAD

**Issue by MahmoudMabrok** [kareemAboelatta/Social-media#2]
![image](https://user-images.githubusercontent.com/13488900/185710831-5b65043a-5be2-4ef4-b025-22bc28fec189.png)
Above i think return type of first method should not be `Task<Any>` as i think Task is related to Firebase itself (if not so no problem with that). 

as we do abstraction layer so it is preferred to not use a source/lib specific return type so it can be used with any source/lib.

**Comment by kareemAboelatta** [comment]
Ok, O I'm going to change it thanks...
